# Generated by Django 5.2 on 2025-06-15 07:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_lesson_groups_module_lesson_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="text",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
