# Generated by Django 5.2 on 2025-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_lesson_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="about",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
