# Generated by Django 5.2 on 2025-06-12 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
        ("structure", "0002_lessontime_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="science",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sciences",
                to="main.school",
            ),
            preserve_default=False,
        ),
    ]
