# Generated by Django 5.2 on 2025-06-13 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure", "0004_rename_semester_studentgroup_academic_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groupmodel_to_academic_year",
                to="structure.academicyear",
            ),
        ),
    ]
