# Generated by Django 5.2 on 2025-06-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structure", "0003_science_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentgroup",
            old_name="semester",
            new_name="academic_year",
        ),
    ]
