# Generated by Django 5.2 on 2025-06-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure", "0005_alter_studentgroup_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
