# Generated by Django 5.2 on 2025-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure", "0006_studentgroup_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="sciencegroup",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
