# Generated by Django 5.2 on 2025-06-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="school/logo/"),
        ),
    ]
